# -*- encoding:utf-8 -*-
"""
    app.py
    ----------------
    
    应用与关于应用的配置设置。
"""
import os

from flask import Flask, render_template
# 导入扩展
from meowcave.extensions import db, migrate
# 导入模型
from meowcave.user.models import User
# 导入视图
from meowcave.auth.forms import LoginForm

def create_app():
    """
        创建应用。
    """
    app = Flask('meowcave')
    
    
    # 确保`../instance`存在
    if not os.path.exists(app.instance_path):
        os.makedirs(app.instance_path)
    
    
    configure_app(app)
    
    
    configure_extensions(app)
    
    
    configure_errorhandlers(app)
    
    
    # 路由
    @app.route('/hello')# index
    def hello():
        return 'Hello, world.'
    
    
    # Login(Temp)
    @app.route('/login')
    def login():
        form = LoginForm()
        return render_template('auth/login.html', title='登录', login_form=form)
    
    
    return app


def configure_app(app):
    """
        应用设置。
    """
    # 缺省设置的导入
    config = app.config.from_object('meowcave.setting.testing.DevelopmentConfig')


def configure_extensions(app):
    """
        关于插件（`flask_xxx`）的初始化设置。
    """
    # 等价于`db = SQLAlchemy(app)`
    db.init_app(app)
    # 等价于`megrate = Megrate(app, db)`
    migrate.init_app(app, db)


def configure_errorhandlers(app):# 对应的模板未完成
    """
        错误异常代码巴拉巴拉
    """
    @app.errorhandler(400)
    def bad_request(e):
        # HTTP 400
        return render_template('errors/400.html', title='Bad request'), 400
    
    
    @app.errorhandler(404)
    def page_not_found(e):
        # HTTP 404
        # “你来到了没有知识的荒原。”
        return render_template('errors/404.html', title='Page not found'), 404
    
    
    @app.errorhandler(418)
    def im_a_teapot(e):
        # HTTP 418
        return 'This page is generated by a TEAPOT.', 418
    
    
    @app.errorhandler(500)
    def internal_server_error(e):
        # HTTP 500
        # “我的锅我的锅 ————admin”
        return render_template('errors/500.html', title='Internal server error'), 500
