"""Add some fuunctions

Revision ID: 1e08302538d6
Revises: 9ad2d7caccde
Create Date: 2022-03-21 14:35:01.059046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e08302538d6'
down_revision = '9ad2d7caccde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credit')
    # ### end Alembic commands ###
